- name: loops 
  hosts: localhost
  tasks: 
    - name: install packages
      ansible.builtin.package:
        msg: "Hello {{ item }}"
      loop:
        - git 
        - postfix
        - mysql

# - name: loops 
#   hosts: localhost
#   become: yes 
#   tasks: 
#     - name: print persons
#       ansible.builtin.debug:
#         msg: "Hello {{ item }}"
#       loop:
#         - Ramesh
#         - Suresh
#         - Juned
