- name: loops 
  hosts: localhost
  tasks: 
    - name: print persons
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
        - Ramesh
        - Suresh
        - Juned

# - name: loops 
#   hosts: localhost
#   become: yes 
#   tasks: 
#     - name: print persons
#       ansible.builtin.debug:
#         msg: "Hello {{ item }}"
#       loop:
#         - Ramesh
#         - Suresh
#         - Juned
